apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm.fullname" . }}-migration
spec:
  template:
    spec:
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "--action=migrate"
      restartPolicy: OnFailure
