apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-viewer-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-viewer
subjects:
  - kind: ServiceAccount
    name: backend
    namespace: default
